"""initial_tables

Revision ID: d301ddf5306f
Revises: 
Create Date: 2026-03-06 19:06:48.457797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd301ddf5306f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonds',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('secid', sa.String(length=50), nullable=False, comment='Ticker code'),
    sa.Column('isin', sa.String(length=20), nullable=True, comment='ISIN code'),
    sa.Column('short_name', sa.String(length=200), nullable=True, comment='Short name'),
    sa.Column('full_name', sa.String(length=500), nullable=True, comment='Full name'),
    sa.Column('board_id', sa.String(length=20), nullable=True, comment='Board: TQCB, TQOB, TQIR'),
    sa.Column('prev_price', sa.Float(), nullable=True, comment='Last close price (% of face)'),
    sa.Column('face_value', sa.Float(), nullable=True, comment='Nominal value (RUB)'),
    sa.Column('accrued_int', sa.Float(), nullable=True, comment='Accrued coupon income (NKD)'),
    sa.Column('lot_size', sa.Integer(), nullable=True, comment='Lot size'),
    sa.Column('yield_at_prev_wa_price', sa.Float(), nullable=True, comment='Yield to maturity (%)'),
    sa.Column('coupon_percent', sa.Float(), nullable=True, comment='Coupon rate (%)'),
    sa.Column('coupon_value', sa.Float(), nullable=True, comment='Coupon payment (RUB)'),
    sa.Column('coupon_period', sa.Integer(), nullable=True, comment='Coupon period (days)'),
    sa.Column('coupon_frequency', sa.Integer(), nullable=True, comment='Coupons per year'),
    sa.Column('mat_date', sa.Date(), nullable=True, comment='Maturity date'),
    sa.Column('offer_date', sa.Date(), nullable=True, comment='Put/call offer date'),
    sa.Column('days_to_maturity', sa.Integer(), nullable=True, comment='Days to maturity'),
    sa.Column('list_level', sa.Integer(), nullable=True, comment='Listing level (1/2/3)'),
    sa.Column('qualified_only', sa.Boolean(), nullable=True, comment='Qualified investors only'),
    sa.Column('security_type', sa.String(length=50), nullable=True, comment='Bond type: ofz, corp, muni'),
    sa.Column('duration', sa.Float(), nullable=True, comment='Duration (days)'),
    sa.Column('volume_today', sa.Float(), nullable=True, comment='Today trading volume (RUB)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last data update'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secid')
    )
    op.create_index(op.f('ix_bonds_board_id'), 'bonds', ['board_id'], unique=False)
    op.create_index('ix_bonds_coupon', 'bonds', ['coupon_percent'], unique=False)
    op.create_index('ix_bonds_days', 'bonds', ['days_to_maturity'], unique=False)
    op.create_index(op.f('ix_bonds_isin'), 'bonds', ['isin'], unique=False)
    op.create_index('ix_bonds_list_level', 'bonds', ['list_level'], unique=False)
    op.create_index(op.f('ix_bonds_mat_date'), 'bonds', ['mat_date'], unique=False)
    op.create_index('ix_bonds_yield', 'bonds', ['yield_at_prev_wa_price'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_qualified', sa.Boolean(), nullable=False, comment='Qualified investor status'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('subscription_until', sa.DateTime(), nullable=True, comment='Subscription end date'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False, comment='Payment amount (RUB)'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='Payment provider'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/success/failed'),
    sa.Column('payload', sa.String(length=500), nullable=True, comment='Provider payload/receipt'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('user_filters',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('price_min', sa.Float(), nullable=True, comment='Min bond price (%)'),
    sa.Column('price_max', sa.Float(), nullable=True, comment='Max bond price (%)'),
    sa.Column('yield_min', sa.Float(), nullable=True, comment='Min yield to maturity (%)'),
    sa.Column('yield_max', sa.Float(), nullable=True, comment='Max yield to maturity (%)'),
    sa.Column('coupon_min', sa.Float(), nullable=True, comment='Min coupon rate (%)'),
    sa.Column('coupon_max', sa.Float(), nullable=True, comment='Max coupon rate (%)'),
    sa.Column('coupon_frequency', sa.Integer(), nullable=True, comment='Exact coupons per year'),
    sa.Column('days_min', sa.Integer(), nullable=True, comment='Min days to maturity'),
    sa.Column('days_max', sa.Integer(), nullable=True, comment='Max days to maturity'),
    sa.Column('qualified_ok', sa.Boolean(), nullable=False, comment='Include qualified-only bonds'),
    sa.Column('list_level_max', sa.Integer(), nullable=True, comment='Max listing level (1=best)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_filters')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_bonds_yield', table_name='bonds')
    op.drop_index(op.f('ix_bonds_mat_date'), table_name='bonds')
    op.drop_index('ix_bonds_list_level', table_name='bonds')
    op.drop_index(op.f('ix_bonds_isin'), table_name='bonds')
    op.drop_index('ix_bonds_days', table_name='bonds')
    op.drop_index('ix_bonds_coupon', table_name='bonds')
    op.drop_index(op.f('ix_bonds_board_id'), table_name='bonds')
    op.drop_table('bonds')
    # ### end Alembic commands ###
